# yaml-language-server: ...
package: api

generate:
  #  types: true
  gorilla-server: true
  models: true
  client: true
  embedded-spec: true

output: ./gen/api.gen.go
output-options:
  user-templates:
    client-with-responses.tmpl: ./templates/client-with-responses.tmpl
    union.tmpl: https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/master/pkg/codegen/templates/union.tmpl
    client.tmpl: ./templates/client.tmpl
    typedef.tmpl: ./templates/types.tmpl
    import.tmpl: ./templates/types.tmpl
    interface.tmpl: ./templates/gorilla/gorilla-interface.tmpl
    register.tmpl: ./templates/gorilla/gorilla-register.tmpl
compatibility:
  apply-gorilla-middleware-first-to-last: true
