# yaml-language-server: ...
package: gen

generate:
  gorilla-server: true
  models: true
  embedded-spec: true
output: ./example/gen/api.gen.go
output-options:
  user-templates:
    gorilla/gorilla-register.tmpl: ./resource/templates/gorilla/gorilla-register.tmpl
    gorilla/gorilla-middleware.tmpl: ./resource/templates/gorilla/gorilla-middleware.tmpl
    gorilla/gorilla-interface.tmpl: ./resource/templates/gorilla/gorilla-interface.tmpl
compatibility:
  apply-gorilla-middleware-first-to-last: true
