name: Build Validation

on:
  push:
    branches:
      - "*"
      - feat/**

jobs:
  generator:
    name: "Generator CLI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: Install dependencies
        run: |
          go mod tidy
      - name: CLI
        run: |
          go run cmd/goserve-generator/main.go -n go-example -u softwareplace -r true -gi false

  validation:
    name: "Build validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: oapi-codegen installer
        run: |
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
      - name: Code Gen Test
        run: |
          rm ./test/gen/api.gen.go || true
          mkdir -p ./test/gen || true
          oapi-codegen --config ./test/resource/config.yaml ./test/resource/pet-store.yaml
      - name: Example test
        run: |
          go test ./...


