name: Build Validation

on:
  push:
    branches:
      - "*"
      - feat/**

jobs:
  validation:
    name: "Build validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: oapi-codegen installer
        run: |
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
      - name: Code Gen Test
        run: |
          ./setup
      - name: Test execution
        run: |
          go test ./...
  generator:
    name: "Generator CLI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: oapi-codegen installer
        run: |
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
      - name: Project setup
        run: |
          ./setup
      - name: Generator validating
        run: |
          go run cmd/goserve-generator/main.go -n go-example -u softwareplace -r true -cgf internal/resource/test_config.yaml -gsv $(shell git rev-parse HEAD) -gi false
  converage:
    name: "Code coverage validator"
    runs-on: ubuntu-latest
    needs:
      - validation
      - generator
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: oapi-codegen installer
        run: |
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
          go install github.com/axw/gocov/gocov@latest
          go install github.com/matm/gocov-html/cmd/gocov-html@latest
      - name: Project setup
        run: |
          ./setup
      - name: Code coverage validator
        run: |
          ./coverage-validator
  

