name: Build Validation

on:
  push:
    branches:
      - "*"

jobs:
  validation:
    name: "Build validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - name: Code Gen Test
        run: |
          rm ./example/gen/api.gen.go
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
          make codegen
      - name: Example test
        run: |
          make test


